program Project2;

uses
  Vcl.Forms,
  Unit2 in 'C:\Users\User\Downloads\Unit2.pas' {Form2},
  CQuery.Ast in '..\Core\CQuery.Ast.pas',
  CQuery.Cases in '..\Core\CQuery.Cases.pas',
  CQuery.Core in '..\Core\CQuery.Core.pas',
  CQuery.Delete in '..\Core\CQuery.Delete.pas',
  CQuery.Expression in '..\Core\CQuery.Expression.pas',
  CQuery.Functions in '..\Core\CQuery.Functions.pas',
  CQuery.FunctionsAbstract in '..\Core\CQuery.FunctionsAbstract.pas',
  CQuery.GroupBy in '..\Core\CQuery.GroupBy.pas',
  CQuery.Having in '..\Core\CQuery.Having.pas',
  CQuery.Insert in '..\Core\CQuery.Insert.pas',
  CQuery.Interfaces in '..\Core\CQuery.Interfaces.pas',
  CQuery.Joins in '..\Core\CQuery.Joins.pas',
  CQuery.Name in '..\Core\CQuery.Name.pas',
  CQuery.NameValue in '..\Core\CQuery.NameValue.pas',
  CQuery.Operators in '..\Core\CQuery.Operators.pas',
  CQuery.OrderBy in '..\Core\CQuery.OrderBy.pas',
  CQuery in '..\Core\CQuery.pas',
  CQuery.Qualifier in '..\Core\CQuery.Qualifier.pas',
  CQuery.Register in '..\Core\CQuery.Register.pas',
  CQuery.Section in '..\Core\CQuery.Section.pas',
  CQuery.Select in '..\Core\CQuery.Select.pas',
  CQuery.Serialize in '..\Core\CQuery.Serialize.pas',
  CQuery.Update in '..\Core\CQuery.Update.pas',
  CQuery.Utils in '..\Core\CQuery.Utils.pas',
  CQuery.Where in '..\Core\CQuery.Where.pas',
  CQuery.FunctionsDB2 in 'CQuery.FunctionsDB2.pas',
  CQuery.FunctionsFirebird in 'CQuery.FunctionsFirebird.pas',
  CQuery.FunctionsInterbase in 'CQuery.FunctionsInterbase.pas',
  CQuery.FunctionsMSSQL in 'CQuery.FunctionsMSSQL.pas',
  CQuery.FunctionsMySQL in 'CQuery.FunctionsMySQL.pas',
  CQuery.FunctionsOracle in 'CQuery.FunctionsOracle.pas',
  CQuery.FunctionsPostgreSQL in 'CQuery.FunctionsPostgreSQL.pas',
  CQuery.FunctionsSQLite in 'CQuery.FunctionsSQLite.pas',
  CQuery.QualifierDB2 in 'CQuery.QualifierDB2.pas',
  CQuery.QualifierFirebird in 'CQuery.QualifierFirebird.pas',
  CQuery.QualifierInterbase in 'CQuery.QualifierInterbase.pas',
  CQuery.QualifierMongoDB in 'CQuery.QualifierMongoDB.pas',
  CQuery.QualifierMSSQL in 'CQuery.QualifierMSSQL.pas',
  CQuery.QualifierMySQL in 'CQuery.QualifierMySQL.pas',
  CQuery.QualifierOracle in 'CQuery.QualifierOracle.pas',
  CQuery.QualifierPostgreSQL in 'CQuery.QualifierPostgreSQL.pas',
  CQuery.QualifierSQLite in 'CQuery.QualifierSQLite.pas',
  CQuery.Select.SQLite in 'CQuery.Select.SQLite.pas',
  CQuery.SelectDB2 in 'CQuery.SelectDB2.pas',
  CQuery.SelectFirebird in 'CQuery.SelectFirebird.pas',
  CQuery.SelectInterbase in 'CQuery.SelectInterbase.pas',
  CQuery.SelectMongoDB in 'CQuery.SelectMongoDB.pas',
  CQuery.SelectMSSQL in 'CQuery.SelectMSSQL.pas',
  CQuery.SelectMySQL in 'CQuery.SelectMySQL.pas',
  CQuery.SelectOracle in 'CQuery.SelectOracle.pas',
  CQuery.SelectPostgreSQL in 'CQuery.SelectPostgreSQL.pas',
  CQuery.SerializeDB2 in 'CQuery.SerializeDB2.pas',
  CQuery.SerializeFirebird in 'CQuery.SerializeFirebird.pas',
  CQuery.SerializeInterbase in 'CQuery.SerializeInterbase.pas',
  CQuery.SerializeMongoDB in 'CQuery.SerializeMongoDB.pas',
  CQuery.SerializeMSSQL in 'CQuery.SerializeMSSQL.pas',
  CQuery.SerializeMySQL in 'CQuery.SerializeMySQL.pas',
  CQuery.SerializeOracle in 'CQuery.SerializeOracle.pas',
  CQuery.SerializePostgreSQL in 'CQuery.SerializePostgreSQL.pas',
  CQuery.SerializeSQLite in 'CQuery.SerializeSQLite.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TForm2, Form2);
  Application.Run;
end.
